name: edge-platform

services:
  edge-gateway:
    pids_limit: 256
    logging: &default-logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    image: edge-platform-edge-gateway:2.0.0
    container_name: edge-platform-edge-gateway
    build:
      context: .
      dockerfile: edge-gateway/Dockerfile
    env_file:
      - .env
    depends_on:
      artifact-repository:
        condition: service_healthy
    ports:
      - "80:8081"
      - "443:8443"
    volumes:
      - ./edge-gateway/config/routes.txt:/etc/nginx/source/routes.txt:ro
    restart: unless-stopped
    networks:
      edge:
        aliases:
          - servicoop-edge-gateway

  artifact-repository:
    pids_limit: 256
    logging: *default-logging
    image: edge-platform-artifact-repository:2.0.0
    container_name: edge-platform-artifact-repository
    build:
      context: .
      dockerfile: artifact-repository/Dockerfile
    volumes:
      - ./volumes/repository:/repository:ro
    restart: unless-stopped
    networks:
      edge:
        aliases:
          - artifact-repository

networks:
  edge:
    name: servicoop-edge-net
